language: node_js
before_script:
- npm install -g bower
- npm install -g karma
- npm install -g karma-cli
- npm install -g babel-cli
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- node ./server/controllers/controller.js
- "./node_modules/protractor/bin/webdriver-manager update"
- "node server/server.js 2>&1 &"
script:
- npm run test-travis
addons:
  sauce_connect: true
  hosts: blood
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: Pt1bDPwbxNshKuTGoaavdTJ7EENYOXLwsG6IupOh+jwdZWueHQH+lZTOo9ndC4sCn00VmaIhHpMYHY3EYj9BHiuRyTwt5l3sotBwz3PcMbxqHz5+w4lZlerK20/bT0eL9/biG/TQLvMvvXRH+P8vv6dSE9xoMciICJZn8T6VZMYn9OgHLed3kyJYQjf9FvcgjGRFKSgTilQl7uhv5HVCrZNXBV50ilIfNNQl1Wyhs3XiRvZiCVtmxlFq/uoWHxC2/L28/GOJ38G92atS7dCWwCBfDp19Mdg0Ypn+KviLcpqT2hfW3K4Un/vEgF+dLqBhWxZr+OrlJZmabrOIrlN9VJO1LwRE24J+MYCUewLNKW8zsrDDnao5bvGSZaO5uQEoAhbrsJkqpHN7zC74mrl7I1mwCI8ZMSotXsy1J8jqKVzN/4/hY/znHWoM2IfU7evyBgGdFdfCa7Dz/G/pdaZJvU0Ax1S/XePLj1RwyWWiPrDfHUVGkN259vNR3UNVh93b95FDYmCsaNWjdOgmcUtU8aaLOHlwxiXn2u77LjZH/lbiRjVHXYYBZpC5emq5MjQvZKTBOqL4NnGauyJOrfxApiTo2o3rOxrYJu8jPHxa2W1Yk08EvHAP5jmq0x3FLTaoOMLXOB2cyNW8vrg30E7Wl94fzv6B1ylKyjVlO0F0598=
  - secure: 20GEDlJp2B9Wg2FJVC0IWQZI/m82Lm7CfkA5JlinqJj1dD8O+U7bzMjwOniTtxWq2gRSFGnlrjAD+coPUpvLm/Hz6q9QT/4bIUvygjP+mLjmoHwmIz7P8RUMzbB5LcHl4REDvFjicOP2D9rmEJRLFtm25+QvP3upGQQQFYFukLzUhzngRbEwiur+5QnxrIxO3ZtoSUyEDltpdTFm6GbRnCobXwq5012RJ5lpeWO045p7T8w9Rjn0g4kWFOqBulU8plykf7dQRgDGW9tk1xtNpZln49NC/Vx8xRoutFTfXRuXP/D7gIshPQBDNc/CcRVCOmfzjciKyfERgipDgrNdur4WawN6nwhAqOgw34QRercqpNzF3mdAAXblJsPuABCHMQj3mlvEZZlBJC8FvzYsMrKuXRKR14Biioj2oUTdCdGxQZqwOsXhriT5Qu7HezDaRgOFC+wC5crVZiSNLO4QVC+vyw4ViLZ2yx8qSwq0JtRP299yPqNlz7fuMc13vedaMfiyY/vvdWuz/sf2JMvJAXj9FuTxPjo/8DrBiKQ0Qnn8db7XTse+XNbJUDdUKTbJ9r5+s9TbyoRxHwzufsaDo8GP3dBVx5WTqq8j6ESTg5CsSQu4J8dgT0MHshw1tJxq/Ymi4iEukEH1zKGlJXNYOxcdcsji3s2Lh5+QVBSg/cE=
node_js:
- 5.9.1
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_073344a26ea2_key -iv $encrypted_073344a26ea2_iv
  -in serverconfig.js.enc -out serverconfig.js -d
- touch serverconfig.js
- mysql -u root -e 'create database blood;'
after_success:
- npm run coverage
- npm run report-coverage
